version: "3.3"
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  extract:
      image: ext-docker
      container_name: extract
      restart: always
      ports:
        - 6200:6200
  transform:
      image: trans-docker
      container_name: transform
      restart: always
      ports:
        - 7000:7000
  load:
      image: load-docker
      container_name: load
      restart: always
      ports:
        - 9000:9000
volumes:
  redis_volume_data:
  redis_insight_volume_data: